In [15]:
import torch
import matplotlib.pyplot as plt
import pandas as pd

import models
import preprocessing as prep
import train

In [16]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [17]:
dtype = torch.float
device = torch.device("cpu")

In [49]:
X_train, X_val, _, y_train, y_val, _ = prep.load_lstm_data('../data/S_data_2019_04_14/', 'train climatewohnzimmer', 143, 3)

(572, 18) (143, 18) (143, 18)


In [50]:
X_train.shape

(142, 143, 13)

In [51]:
x = torch.from_numpy(X_train[:,0:1,:]).to(device).type(dtype)

In [52]:
x.shape

torch.Size([142, 1, 13])

In [53]:
len(X_train)

142

In [54]:
y_train.shape

(142, 3)

In [55]:
X_train.transpose(1,0,2).shape

(143, 142, 13)

In [56]:
model = models.Lstm(X_train.shape[2], 256, 143, 'LSTM1', 3, 2, dtype, device, False, 0.0)

In [57]:
experiment_path = '../experiments/exp1/'

In [58]:
training = train.TrainLstm(model, X_train, X_val, y_train, y_val, experiment_path)

In [ ]:
training.run_train(150)

Epoch  0  train_loss:  423.8971862792969 validate_loss:  326.5793762207031 Time  5.0937910079956055
Epoch  10  train_loss:  8.877848625183105 validate_loss:  2.5342516899108887 Time  47.99062418937683
Epoch  20  train_loss:  18.8065242767334 validate_loss:  14.180120468139648 Time  72.05126309394836
Epoch  30  train_loss:  0.8940895199775696 validate_loss:  0.88222736120224 Time  80.18630409240723
Epoch  40  train_loss:  0.8466129302978516 validate_loss:  0.787446141242981 Time  87.62563395500183
Epoch  50  train_loss:  0.8415781855583191 validate_loss:  0.7564544677734375 Time  82.53709697723389
Epoch  60  train_loss:  0.7194679975509644 validate_loss:  0.7196484804153442 Time  77.64471387863159
Epoch  70  train_loss:  0.7059161067008972 validate_loss:  0.7084074020385742 Time  71.28235912322998
Epoch  80  train_loss:  0.700415849685669 validate_loss:  0.7008477449417114 Time  62.472134828567505


In [ ]:
model.batch_size

In [ ]:
loss = pd.read_csv(experiment_path+'errors__LSTM1__.csv')

In [ ]:
loss_val = pd.read_csv(experiment_path+'errors_val__LSTM1__.csv')

In [ ]:
plt.plot(loss[50:]);
plt.plot(loss_val[50:]);

In [ ]:
x_train, x_val, x_test, y_train, y_val, y_test = prep.load_lstm_data('../data/M_data_2019_04_16/', 'train climateschlafzimmer', 1, 1)

In [51]:
import torch.nn as nn

In [52]:
rnn = nn.LSTM(10, 20, 2)

In [53]:
input = torch.randn(5, 3, 10)

In [54]:
input.shape

torch.Size([5, 3, 10])

In [55]:
input

tensor([[[ 7.5614e-01,  1.2167e+00, -3.1603e-01, -2.3895e+00,  4.8381e-01,
           7.2968e-01, -1.3157e+00,  5.6672e-01,  1.9504e+00, -9.6870e-01],
         [-1.0779e-01, -1.5469e-01,  1.7124e-01,  1.7076e-01,  1.3271e+00,
           1.0206e+00,  5.4443e-01, -3.5456e-01, -9.6861e-01,  5.7230e-01],
         [-1.4201e+00,  4.3215e-01, -7.7455e-01, -1.3862e+00, -4.2180e-01,
           3.9410e-01, -9.2836e-01,  1.0058e-01, -8.1319e-01,  4.7307e-01]],

        [[ 2.0755e+00,  5.2099e-02,  1.6467e-01, -3.8166e+00, -1.7683e+00,
           9.1415e-01, -6.7080e-01, -1.1066e+00, -5.7552e-01, -5.7920e-01],
         [-2.2985e-01, -2.6706e-01, -1.7503e-01, -1.2458e+00, -3.3201e-01,
           6.4765e-01, -6.3130e-01,  1.9835e-01, -4.8055e-02,  9.3250e-01],
         [-1.2004e-01, -1.9546e-01, -5.6920e-02,  7.8474e-01, -2.5136e-02,
           3.0537e-01, -3.1005e+00,  2.5692e-01, -1.2426e+00,  6.6220e-01]],

        [[-3.0697e-01,  1.4106e-01, -1.2720e+00,  5.6953e-01, -2.1962e-01,
          -4.27

In [56]:
h0 = torch.zeros(2, 3, 20)

In [57]:
h0.shape

torch.Size([2, 3, 20])

In [58]:
c0 = torch.zeros(2, 3, 20)

In [59]:
output, (hn, cn) = rnn(input, (h0, c0))

In [60]:
output.shape

torch.Size([5, 3, 20])

In [61]:
out = nn.Linear(20, 1)

In [62]:
y_pred = out(output)

In [63]:
y_pred.shape

torch.Size([5, 3, 1])

In [64]:
y_pred.view(len(y_pred),-1).view(-1)

tensor([0.1671, 0.1617, 0.1720, 0.1729, 0.1615, 0.1586, 0.1681, 0.1787, 0.1595,
        0.1603, 0.1658, 0.1660, 0.1495, 0.1633, 0.1681],
       grad_fn=<ViewBackward>)

In [65]:
y_pred.detach()[:,:,:]

tensor([[[0.1671],
         [0.1617],
         [0.1720]],

        [[0.1729],
         [0.1615],
         [0.1586]],

        [[0.1681],
         [0.1787],
         [0.1595]],

        [[0.1603],
         [0.1658],
         [0.1660]],

        [[0.1495],
         [0.1633],
         [0.1681]]])